version: "3"

services:
  gridsome:
    build:
      # context配下のDockefileを参照する
      context: "./gridsome"
      dockerfile: "Dockerfile"
    container_name: gridsome
    ports:
      # 左がホスト，右がコンテナ
      - 8080:8080
    # 作業ディレクトリ
    working_dir: /app/my-blog
    # コンテナを立ち上げ続ける
    tty: true
    volumes:
      - ./app/my-blog:/app/my-blog
    # 実行するコマンド
    command: sh -c "gridsome develop"

  strapi:
    build:
      context: "./strapi"
      dockerfile: "Dockerfile"
    container_name: strapi
    working_dir: /app/my-blog-api
    ports:
      - 8081:1337
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./app/my-blog-api:/app/my-blog-api
    command: sh -c "yarn develop"

  mysql:
    container_name: mysql
    image: "mysql:5.7"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: "nginx:1.19.1-alpine"
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - strapi
      - mysql
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
